Zadanie 7.3
Jola-Witaszak/Jola-Witaszak-Kodilla-java pull request #10
Opened 2020-10-31 18:15 UTC by Jola-Witaszak

2020-11-01 22:55 UTC, mps4dev requested changes
👎

2020-11-01 22:55 UTC, mps4dev commented on src/main/java/com/kodilla/stream/forumuser/Forum.java
> +        listOfForumUsers.add(new ForumUser(101, "Mark-T", 'M', 1995,12,12,63));
takich rzeczy nie robimy w klasie odpowiedzialnej za logike biznesowa. W konstruktorze trzeba przekazac ta liste.

2020-11-01 22:55 UTC, mps4dev commented on src/main/java/com/kodilla/stream/forumuser/ForumUser.java
> +    private  char sex = 'M'/ 'F';
a co to jest? Przede wszystkich private final. 
Po drugie, typ char jest konwertowalny na int, a wiec 'M' / 'F' to jest dzielenie dwoch liczb. Tu ma byc jeden znak, kry ma byc ustawiony w konstruktorze.

2020-11-01 22:55 UTC, mps4dev commented on src/main/java/com/kodilla/stream/forumuser/StreamMain.java
> +        Forum forum = new Forum();
tutaj musisz miec metode private static List<ForumUser> init() { ... }

2020-11-01 22:55 UTC, mps4dev commented on src/main/java/com/kodilla/stream/forumuser/StreamMain.java
> +                .filter(forumUser -> forumUser.getBirthDate().getYear() >= 2000)
Jak ktos urodzil sie 30 grudnia 2000 to nie ma 20 lat jeszcze

2020-11-06 09:01 UTC, Jola-Witaszak commented on src/main/java/com/kodilla/stream/forumuser/Forum.java
> +    public Forum(List<ForumUser> listOfForumUsers) {
final List... raczej? :/

2020-11-06 09:02 UTC, Jola-Witaszak commented on src/main/java/com/kodilla/stream/forumuser/Forum.java
> +        this.listOfForumUsers = listOfForumUsers;
final List... raczej? :/

2020-11-07 08:55 UTC, mps4dev approved these changes
👍

2020-11-07 15:04 UTC, merged