task-15.2 "Prototype - deepCopy(), shallowCopy()"
Jola-Witaszak/Jola-Witaszak-Kodilla-java pull request #34
Opened 2021-01-01 17:08 UTC by Jola-Witaszak

2021-01-01 17:10 UTC, Jola-Witaszak commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertEquals(12, deepClonedLibrary.getBooks().size());
Warning:() Method invocation 'getBooks' may produce 'NullPointerException'
linie 42 i 43... z tym trzeba coś robić?

2021-01-02 08:32 UTC, mps4dev requested changes
👎

2021-01-02 08:32 UTC, mps4dev commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +            clonedLibrary.getBooks().add(book);
i tu nie bedzie deep copy. Jesli zmienie ksiazke w jednej bibliotece, to bedzie zmieniona rowniez w tej drugiej. Pamietaj, ze w Javie mamy przekazywanie argumentow do metod przez wartosc referencji.
np. Book book = new Book("Ogniem i mieczem", "Sienkiewicz", 1913);
      List<Book> listA = Arrays.asList(book);
      List<Book> listB = Arrays.asList(book);
      listA.get(0).author = "Mickiewicz";
      listB.get(0).getAuthor() ====> "Mickiewicz"

2021-01-02 08:32 UTC, mps4dev commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertEquals(12, deepClonedLibrary.getBooks().size());
w tescie nie

2021-01-21 20:36 UTC, mps4dev approved these changes
👍

2021-01-21 20:36 UTC, mps4dev commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +            clonedLibrary.getBooks().add(book);
clonedLibrary.getBooks().add(new Book(book.getTitle(), book.getAuthor(), book.getPublicationYear()));

2021-03-07 11:17 UTC, merged