task-17.2 "TaskListDao"
Jola-Witaszak/Jola-Witaszak-Kodilla-java pull request #48
Opened 2021-01-17 14:56 UTC by Jola-Witaszak

2021-01-17 14:57 UTC, Jola-Witaszak commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +
wszystkie nazwy ustawione dla tabeli i kolumn mam Error: Cannot resolve... ale test przechodzi :/

2021-01-17 15:47 UTC, mps4dev requested changes
👎

2021-01-17 15:47 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +@Table(name = "taskLists")
proponuje w kodzie nazwy z bazy danych pisac duzymi literami wylacznie : TASKLISTS (tak tez bylo w module)

2021-01-17 15:47 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +    @NotNull
zbedne (@Id juz zapewnia, ze nie bedzie nullem)

2021-01-17 15:47 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +    @Column(name = "id", unique = true)
zbedne

2021-01-17 15:47 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +    @Column(name = "listName")
LISTNAME

2021-01-17 15:47 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +    @Column(name = "description")
jw.

2021-01-17 15:47 UTC, mps4dev commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/tasklist/dao/TaskListDaoTestSuite.java
> +        int id = downLoadedList.get(0).getId();
A moze by tu uzyc deleteAll?

2021-01-17 16:14 UTC, Jola-Witaszak commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +
a settery niestety publiczne. Wszystkie...

2021-01-18 08:47 UTC, mps4dev requested changes
👎

2021-01-18 08:47 UTC, mps4dev commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/tasklist/TaskList.java
> +    private void setId(int id) {
czemu private?

2021-01-18 08:47 UTC, mps4dev commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/tasklist/dao/TaskListDaoTestSuite.java
> +        taskListDao.deleteAll();
jednak wroc do tego co bylo :) przepraszam. Ale w tescie moglibysmy usunac tu cala tabelke.

2021-01-18 23:05 UTC, mps4dev approved these changes
👍

2021-01-19 17:26 UTC, merged