Task 6.6
Jola-Witaszak/Jola-Witaszak-Kodilla-java pull request #5
Opened 2020-10-24 12:52 UTC by Jola-Witaszak

2020-10-24 13:01 UTC, Jola-Witaszak commented on kodilla-testing/src/main/java/com/kodilla/testing/library/BookLibrary.java
> +    }
metoda sciągnięta z internetu :) kompletnie nie wiem o co tu chodzi

2020-10-26 22:32 UTC, mps4dev requested changes
👎

2020-10-26 22:32 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/library/BookLibrary.java
> +    }
Z jakiego internetu?

2020-10-26 22:32 UTC, mps4dev commented on kodilla-testing/src/test/java/com/kodilla/testing/library/BookDirectoryTestSuite.java
> +        //Given
co mowi nazwa tej metody testujacej?

2020-10-26 22:32 UTC, mps4dev commented on kodilla-testing/src/test/java/com/kodilla/testing/library/BookDirectoryTestSuite.java
> +        BookLibrary bookLibrary = new BookLibrary(libraryDatabaseMock);
a gdzie jest ten mock zdefiniowany?

2020-10-26 22:32 UTC, mps4dev commented on kodilla-testing/src/test/java/com/kodilla/testing/library/BookDirectoryTestSuite.java
> +    void testListBooksInHandsOfBooks_1_() {
Co mowi nazwa tej metody testujacej?

2020-11-07 18:51 UTC, mps4dev approved these changes
👍

2021-01-04 18:09 UTC, merged