Testy do zadania 6.7
Jola-Witaszak/Jola-Witaszak-Kodilla-java pull request #6
Opened 2020-10-25 09:52 UTC by Jola-Witaszak

2020-10-25 09:59 UTC, Jola-Witaszak commented on src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestSuite.java
> +        }
wszystkie testy gdzie jest assertEquals expected 0 są zielone...

2020-10-25 09:59 UTC, Jola-Witaszak commented on src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestSuite.java
> +        }
Wszystkie testy gdzie assertEquals expected >0 są żółte, ale mają assertion failed error...

2020-10-25 10:32 UTC, Jola-Witaszak commented on src/main/java/com/kodilla/testing/forum/statistics/ForumStatistics.java
> +    }
metoda jest do poprawki, bo testy nie przechodzą ...

2020-10-25 13:14 UTC, Jola-Witaszak commented on src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestSuite.java
> +            assertEquals(0.0, result_users100_posts0, 0.01);
teraz mam NaN :) Chyba nie ma sensu pisać testów dla dzielenia z 0

2020-10-26 22:35 UTC, mps4dev requested changes
👎

2020-10-26 22:35 UTC, mps4dev commented on src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestSuite.java
> +    @org.jetbrains.annotations.NotNull
tej adnotacji nie uzywamy

2020-10-26 22:35 UTC, mps4dev commented on src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestSuite.java
> +    private List<String> generateListOfNUsers (int usersQuantity) {
do czego ponizsze prywatne metody? Mamy mokowanie.

2020-11-01 22:50 UTC, mps4dev approved these changes
👍

2020-11-02 16:03 UTC, merged